### PR TITLE
fix for gnome shell 3.38

### PR DESCRIPTION
**Pull request by Keridos**
Thanks to https://extensions.gnome.org/accounts/profile/pemmoura

### CODE REVIEW

**Comment by ChWick** [comment]
I simply removed the import since it was not required at all. This should not break the code for older gnome shell versions

**Comment by Keridos** [comment]
Could you update it on extension.gnome.org please?

**Comment by ChWick** [comment]
I submitted the new extension version, it takes a few days for the review process.

**Comment by ChWick** [comment]
@Keridos  FYI: The new version is available on extension.gnome.org

**Pull request closed without merging**
